# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alimento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.CharField(choices=[('1', 'Carne'), ('2', 'Pescado'), ('3', 'Lacteo'), ('4', 'Fruta'), ('5', 'Otra')], default=5, max_length=1),
        ),
    ]
