# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20170614_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.CharField(choices=[('Carne', 'Carne'), ('Pescado', 'Pescado'), ('Lacteo', 'Lacteo'), ('Fruta', 'Fruta'), ('Otra', 'Otra')], default=5, max_length=10),
        ),
    ]
